#!/bin/bash
#tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
#tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
#tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string

#rm -f nohup.out && bash -ic 'nohup ./tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock new-session -d & disown -a'
./tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
./tmate -S /tmp/tmate.sock wait tmate-ready
./tmate -S /tmp/tmate.sock display -p 'Connect with SSH address: #{tmate_ssh}'
./tmate -S /tmp/tmate.sock display -p 'Connect with web: #{tmate_web}'
touch /tmp/keepalive
